apiVersion: tekton.dev/v1beta1 
kind: Task 
metadata: 
  name: echo 
spec:
  params: 
    - name: message
      description: The message echo
      type: string
  steps: 
    - name: echo-message
      image: alpine:3 
      command: [/bin/echo] 
      args: ["$(params.message)"]
---
apiVersion: tekton.dev/v1beta1 
kind: Task 
metadata: 
  name: checkout 
spec:
  params: 
    - name: repo-url
      description: The URL of the github
      type: string
    - name: branch
      description: The bracnh to clone
      type: string
  steps: 
    - name: checkout
      image: bitnamilegacy/git:latest
      command: [git] 
      args: ["clone", "--branch", "$(params.branch)", "$(params.repo-url)"]